### ISSUE TITLE
Bug: indexing with cdxj causes a panic

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarcserver#11]
**Describe the bug**
gowarcserver panics when i try to index ``testdata/IAH-20080430204825-00000-blackbook.warc`` 

**To Reproduce**
1. checkout branch in pr #3 (badger-control in fork)
2.  run gowarcserver index with ``-f cdxj`` i.e ``./warcserver index -f cdxj ./testdata/IAH-20080430204825-00000-blackbook.warc``

**Expected behavior**
gowarcserver should index the files or report a user error to the terminal.

**Additional context**
```bash
[akselhjerpbakk@localhost gowarcserver]$ ./warcserver index -f cdxj ./testdata/IAH-20080430204825-00000-blackbook.warc 
Using config file: /home/akselhjerpbakk/Projects/warcproject/gowarcserver/config.yaml
Format: cdxj
Count:  2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x91749c]

goroutine 1 [running]:
github.com/golang/protobuf/jsonpb.(*jsonWriter).marshalMessage(0xc0001c9aa0, 0xcd9ba0, 0xc0001d4a00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/akselhjerpbakk/go/pkg/mod/github.com/golang/protobuf@v1.4.0-rc.4/jsonpb/encode.go:219 +0x73c
github.com/golang/protobuf/jsonpb.(*Marshaler).marshal(0x0, 0xccfca0, 0xc0001d4a00, 0x32, 0x2e2, 0xc0001d4a00, 0xc000330040, 0x0)
        /home/akselhjerpbakk/go/pkg/mod/github.com/golang/protobuf@v1.4.0-rc.4/jsonpb/encode.go:116 +0x207
github.com/golang/protobuf/jsonpb.(*Marshaler).MarshalToString(...)
        /home/akselhjerpbakk/go/pkg/mod/github.com/golang/protobuf@v1.4.0-rc.4/jsonpb/encode.go:78
github.com/nlnwa/gowarcserver/pkg/index.(*CdxJ).Write(0xc000010268, 0xcd4920, 0xc00007cd40, 0x7ffee18cb20a, 0x32, 0x2e2, 0x0, 0x0)
        /home/akselhjerpbakk/Projects/warcproject/gowarcserver/pkg/index/indexwriter.go:74 +0xe6
github.com/nlnwa/gowarcserver/cmd/warcserver/cmd/index.readFile(0xc0001dc5a0, 0x0, 0x0)
        /home/akselhjerpbakk/Projects/warcproject/gowarcserver/cmd/warcserver/cmd/index/index.go:120 +0x15f
github.com/nlnwa/gowarcserver/cmd/warcserver/cmd/index.runE(0xc0001dc5a0, 0x0, 0x0)
        /home/akselhjerpbakk/Projects/warcproject/gowarcserver/cmd/warcserver/cmd/index/index.go:92 +0xf0
github.com/nlnwa/gowarcserver/cmd/warcserver/cmd/index.NewCommand.func2(0xc0001d3400, 0xc0001dc780, 0x1, 0x3, 0x0, 0x0)
        /home/akselhjerpbakk/Projects/warcproject/gowarcserver/cmd/warcserver/cmd/index/index.go:79 +0xba
github.com/spf13/cobra.(*Command).execute(0xc0001d3400, 0xc0001dc6f0, 0x3, 0x3, 0xc0001d3400, 0xc0001dc6f0)
        /home/akselhjerpbakk/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d2f00, 0xc000000180, 0xc0001c9f78, 0x4118e5)
        /home/akselhjerpbakk/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/akselhjerpbakk/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/akselhjerpbakk/Projects/warcproject/gowarcserver/cmd/warcserver/main.go:27 +0x2b
```

**Comment by Avokadoen** [comment]
After some investigation, the master does not actually has this bug. PR #3  does

**Comment by Avokadoen** [comment]
91e1a4ad5e162bc12e1657e5f4e57c1456f6619b closes this issue
